### ISSUE TITLE
incorrect repository structure and repository name.

### ISSUE THREAD

**Issue by danmarsden** [rajurana/fastassignment#1]
your plugin files should not sit within a "fastassignment" folder within this repository - please put the files into the "root" directory of the repository - this allows organisations to use git submodules and subtrees to install your plugin.

The repository name "https://github.com/rajurana/fastassignment" is also incorrect - please use our frankenstyle naming convention to make it easy for people to identify your plugin - the correct name in your case would be:
https://github.com/rajurana/moodle-mod_fastassignment

for an example of this see:
https://github.com/PoetOS/moodle-mod_questionnaire

**Comment by rajurana** [comment]
Repositiry structure and name is fixed now.
